/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/generateUtilities.ts
 *
 * Type guards and property extractors generated from JSON schemas
 */

import type { SURefMetaEntity } from './types/index.js'
// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard to check if an entity is a Ability
 * @param entity - The entity to check
 * @returns True if the entity is a Ability
 */
export function isAbility(entity: SURefMetaEntity): entity is SURefAbility {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'tree' in entity &&
    'level' in entity
  )
}

/**
 * Type guard to check if an entity is a AbilityTreeRequirement
 * @param entity - The entity to check
 * @returns True if the entity is a AbilityTreeRequirement
 */
export function isAbilityTreeRequirement(
  entity: SURefMetaEntity
): entity is SURefMetaAbilityTreeRequirement {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'requirement' in entity
  )
}

/**
 * Type guard to check if an entity is a BioTitan
 * @param entity - The entity to check
 * @returns True if the entity is a BioTitan
 */
export function isBioTitan(entity: SURefMetaEntity): entity is SURefBioTitan {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'structurePoints' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Chassis
 * @param entity - The entity to check
 * @returns True if the entity is a Chassis
 */
export function isChassis(entity: SURefMetaEntity): entity is SURefChassis {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'chassisAbilities' in entity &&
    'patterns' in entity
  )
}

/**
 * Type guard to check if an entity is a CoreClass
 * @param entity - The entity to check
 * @returns True if the entity is a CoreClass
 */
export function isCoreClass(entity: SURefMetaEntity): entity is SURefCoreClass {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'maxAbilities' in entity &&
    'advanceable' in entity &&
    'coreTrees' in entity
  )
}

/**
 * Type guard to check if an entity is a CrawlerBay
 * @param entity - The entity to check
 * @returns True if the entity is a CrawlerBay
 */
export function isCrawlerBay(entity: SURefMetaEntity): entity is SURefCrawlerBay {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'damagedEffect' in entity &&
    'npc' in entity
  )
}

/**
 * Type guard to check if an entity is a CrawlerTechLevel
 * @param entity - The entity to check
 * @returns True if the entity is a CrawlerTechLevel
 */
export function isCrawlerTechLevel(entity: SURefMetaEntity): entity is SURefMetaCrawlerTechLevel {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'techLevel' in entity &&
    'structurePoints' in entity &&
    'populationMin' in entity &&
    'populationMax' in entity
  )
}

/**
 * Type guard to check if an entity is a Crawler
 * @param entity - The entity to check
 * @returns True if the entity is a Crawler
 */
export function isCrawler(entity: SURefMetaEntity): entity is SURefCrawler {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'npc' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Creature
 * @param entity - The entity to check
 * @returns True if the entity is a Creature
 */
export function isCreature(entity: SURefMetaEntity): entity is SURefCreature {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'hitPoints' in entity
  )
}

/**
 * Type guard to check if an entity is a Distance
 * @param entity - The entity to check
 * @returns True if the entity is a Distance
 */
export function isDistance(entity: SURefMetaEntity): entity is SURefDistance {
  return 'id' in entity && 'name' in entity && 'source' in entity && 'page' in entity
}

/**
 * Type guard to check if an entity is a Drone
 * @param entity - The entity to check
 * @returns True if the entity is a Drone
 */
export function isDrone(entity: SURefMetaEntity): entity is SURefDrone {
  return 'id' in entity && 'name' in entity && 'source' in entity && 'page' in entity
}

/**
 * Type guard to check if an entity is a Equipment
 * @param entity - The entity to check
 * @returns True if the entity is a Equipment
 */
export function isEquipment(entity: SURefMetaEntity): entity is SURefEquipment {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Keyword
 * @param entity - The entity to check
 * @returns True if the entity is a Keyword
 */
export function isKeyword(entity: SURefMetaEntity): entity is SURefKeyword {
  return 'id' in entity && 'name' in entity && 'source' in entity && 'page' in entity
}

/**
 * Type guard to check if an entity is a Meld
 * @param entity - The entity to check
 * @returns True if the entity is a Meld
 */
export function isMeld(entity: SURefMetaEntity): entity is SURefMeld {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a NPC
 * @param entity - The entity to check
 * @returns True if the entity is a NPC
 */
export function isNPC(entity: SURefMetaEntity): entity is SURefNPC {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'hitPoints' in entity
  )
}

/**
 * Type guard to check if an entity is a RollTable
 * @param entity - The entity to check
 * @returns True if the entity is a RollTable
 */
export function isRollTable(entity: SURefMetaEntity): entity is SURefRollTable {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'section' in entity &&
    'table' in entity
  )
}

/**
 * Type guard to check if an entity is a Squad
 * @param entity - The entity to check
 * @returns True if the entity is a Squad
 */
export function isSquad(entity: SURefMetaEntity): entity is SURefSquad {
  return (
    'id' in entity &&
    'name' in entity &&
    'source' in entity &&
    'page' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Trait
 * @param entity - The entity to check
 * @returns True if the entity is a Trait
 */
export function isTrait(entity: SURefMetaEntity): entity is SURefTrait {
  return 'id' in entity && 'name' in entity && 'source' in entity && 'page' in entity
}

/**
 * Type guard to check if an entity is a Vehicle
 * @param entity - The entity to check
 * @returns True if the entity is a Vehicle
 */
export function isVehicle(entity: SURefMetaEntity): entity is SURefVehicle {
  return 'id' in entity && 'name' in entity && 'source' in entity && 'page' in entity
}

// Import types used in type guards
import type {
  SURefAbility,
  SURefBioTitan,
  SURefChassis,
  SURefCoreClass,
  SURefCrawler,
  SURefCrawlerBay,
  SURefCreature,
  SURefDistance,
  SURefDrone,
  SURefEquipment,
  SURefKeyword,
  SURefMeld,
  SURefMetaAbilityTreeRequirement,
  SURefMetaCrawlerTechLevel,
  SURefNPC,
  SURefRollTable,
  SURefSquad,
  SURefTrait,
  SURefVehicle,
} from './types/index.js'
// ============================================================================
// PROPERTY EXTRACTORS
// ============================================================================

/**
 * Extract asset_url from an entity
 * @param entity - The entity to extract from
 * @returns The asset_url or undefined
 */
export function getAsset_url(entity: SURefMetaEntity): string | undefined {
  return 'asset_url' in entity && typeof entity.asset_url === 'string'
    ? entity.asset_url
    : undefined
}

/**
 * Extract content from an entity
 * @param entity - The entity to extract from
 * @returns The content or undefined
 */
export function getContent(entity: SURefMetaEntity): unknown | undefined {
  return 'content' in entity ? entity.content : undefined
}

/**
 * Extract id from an entity
 * @param entity - The entity to extract from
 * @returns The id or undefined
 */
export function getId(entity: SURefMetaEntity): string | undefined {
  return 'id' in entity && typeof entity.id === 'string' ? entity.id : undefined
}

/**
 * Extract indexable from an entity
 * @param entity - The entity to extract from
 * @returns The indexable or undefined
 */
export function getIndexable(entity: SURefMetaEntity): boolean | undefined {
  return 'indexable' in entity && typeof entity.indexable === 'boolean'
    ? entity.indexable
    : undefined
}

/**
 * Extract blackMarket from an entity
 * @param entity - The entity to extract from
 * @returns The blackMarket or undefined
 */
export function getBlackMarket(entity: SURefMetaEntity): boolean | undefined {
  return 'blackMarket' in entity && typeof entity.blackMarket === 'boolean'
    ? entity.blackMarket
    : undefined
}

/**
 * Extract name from an entity
 * @param entity - The entity to extract from
 * @returns The name or undefined
 */
export function getName(entity: SURefMetaEntity): string | undefined {
  return 'name' in entity && typeof entity.name === 'string' ? entity.name : undefined
}

/**
 * Extract source from an entity
 * @param entity - The entity to extract from
 * @returns The source or undefined
 */
export function getSource(entity: SURefMetaEntity): unknown | undefined {
  return 'source' in entity ? entity.source : undefined
}

/**
 * Extract page from an entity
 * @param entity - The entity to extract from
 * @returns The page or undefined
 */
export function getPage(entity: SURefMetaEntity): number | undefined {
  return 'page' in entity && typeof entity.page === 'number' ? entity.page : undefined
}

/**
 * Extract actions from an entity
 * Note: This function returns the raw string array. Use extractActions() from utilities.ts
 * to get resolved action objects.
 * @param entity - The entity to extract from
 * @returns The actions or undefined
 */
export function getActions(entity: SURefMetaEntity): unknown | undefined {
  return 'actions' in entity ? entity.actions : undefined
}

/**
 * Extract structurePoints from an entity
 * @param entity - The entity to extract from
 * @returns The structurePoints or undefined
 */
export function getStructurePoints(entity: SURefMetaEntity): number | undefined {
  return 'structurePoints' in entity && typeof entity.structurePoints === 'number'
    ? entity.structurePoints
    : undefined
}

/**
 * Extract traits from an entity
 * @param entity - The entity to extract from
 * @returns The traits or undefined
 */
export function getTraits(entity: SURefMetaEntity): SURefObjectTrait[] | undefined {
  return 'traits' in entity && Array.isArray(entity.traits) ? entity.traits : undefined
}

/**
 * Extract techLevel from an entity
 * @param entity - The entity to extract from
 * @returns The techLevel or undefined
 */
export function getTechLevel(entity: SURefMetaEntity): unknown | undefined {
  return 'techLevel' in entity ? entity.techLevel : undefined
}

/**
 * Extract salvageValue from an entity
 * @param entity - The entity to extract from
 * @returns The salvageValue or undefined
 */
export function getSalvageValue(entity: SURefMetaEntity): unknown | undefined {
  return 'salvageValue' in entity ? entity.salvageValue : undefined
}

/**
 * Extract hitPoints from an entity
 * @param entity - The entity to extract from
 * @returns The hitPoints or undefined
 */
export function getHitPoints(entity: SURefMetaEntity): unknown | undefined {
  return 'hitPoints' in entity ? entity.hitPoints : undefined
}

/**
 * Extract npc from an entity
 * @param entity - The entity to extract from
 * @returns The npc or undefined
 */
export function getNpc(entity: SURefMetaEntity): SURefObjectNpc | undefined {
  return 'npc' in entity &&
    entity.npc !== null &&
    typeof entity.npc === 'object' &&
    !Array.isArray(entity.npc)
    ? entity.npc
    : undefined
}

/**
 * Extract energyPoints from an entity
 * @param entity - The entity to extract from
 * @returns The energyPoints or undefined
 */
export function getEnergyPoints(entity: SURefMetaEntity): number | undefined {
  return 'energyPoints' in entity && typeof entity.energyPoints === 'number'
    ? entity.energyPoints
    : undefined
}

/**
 * Extract heatCapacity from an entity
 * @param entity - The entity to extract from
 * @returns The heatCapacity or undefined
 */
export function getHeatCapacity(entity: SURefMetaEntity): number | undefined {
  return 'heatCapacity' in entity && typeof entity.heatCapacity === 'number'
    ? entity.heatCapacity
    : undefined
}

/**
 * Extract systemSlots from an entity
 * @param entity - The entity to extract from
 * @returns The systemSlots or undefined
 */
export function getSystemSlots(entity: SURefMetaEntity): number | undefined {
  return 'systemSlots' in entity && typeof entity.systemSlots === 'number'
    ? entity.systemSlots
    : undefined
}

/**
 * Extract moduleSlots from an entity
 * @param entity - The entity to extract from
 * @returns The moduleSlots or undefined
 */
export function getModuleSlots(entity: SURefMetaEntity): number | undefined {
  return 'moduleSlots' in entity && typeof entity.moduleSlots === 'number'
    ? entity.moduleSlots
    : undefined
}

/**
 * Extract cargoCapacity from an entity
 * @param entity - The entity to extract from
 * @returns The cargoCapacity or undefined
 */
export function getCargoCapacity(entity: SURefMetaEntity): number | undefined {
  return 'cargoCapacity' in entity && typeof entity.cargoCapacity === 'number'
    ? entity.cargoCapacity
    : undefined
}

/**
 * Extract choices from an entity
 * @param entity - The entity to extract from
 * @returns The choices or undefined
 */
export function getChoices(entity: SURefMetaEntity): SURefObjectChoice[] | undefined {
  return 'choices' in entity && Array.isArray(entity.choices) ? entity.choices : undefined
}

/**
 * Extract table from an entity
 * @param entity - The entity to extract from
 * @returns The table or undefined
 */
export function getTable(entity: SURefMetaEntity): SURefObjectTable | undefined {
  return 'table' in entity &&
    entity.table !== null &&
    typeof entity.table === 'object' &&
    !Array.isArray(entity.table)
    ? entity.table
    : undefined
}

/**
 * Extract systems from an entity
 * @param entity - The entity to extract from
 * @returns The systems or undefined
 */
export function getSystems(entity: SURefMetaEntity): unknown | undefined {
  return 'systems' in entity ? entity.systems : undefined
}

/**
 * Extract description from an entity
 * @param entity - The entity to extract from
 * @returns The description or undefined
 */
export function getDescription(entity: SURefMetaEntity): string | undefined {
  return 'description' in entity && typeof entity.description === 'string'
    ? entity.description
    : undefined
}

/**
 * Extract tree from an entity
 * @param entity - The entity to extract from
 * @returns The tree or undefined
 */
export function getTree(entity: SURefMetaEntity): unknown | undefined {
  return 'tree' in entity ? entity.tree : undefined
}

/**
 * Extract level from an entity
 * @param entity - The entity to extract from
 * @returns The level or undefined
 */
export function getLevel(entity: SURefMetaEntity): unknown | undefined {
  return 'level' in entity ? entity.level : undefined
}

/**
 * Extract mechActionType from an entity
 * @param entity - The entity to extract from
 * @returns The mechActionType or undefined
 */
export function getMechActionType(entity: SURefMetaEntity): unknown | undefined {
  return 'mechActionType' in entity ? entity.mechActionType : undefined
}

/**
 * Extract grants from an entity
 * @param entity - The entity to extract from
 * @returns The grants or undefined
 */
export function getGrants(entity: SURefMetaEntity): SURefObjectGrant[] | undefined {
  return 'grants' in entity && Array.isArray(entity.grants) ? entity.grants : undefined
}

/**
 * Extract activationCurrency from an entity
 * @param entity - The entity to extract from
 * @returns The activationCurrency or undefined
 */
export function getActivationCurrency(entity: SURefMetaEntity): string | undefined {
  return 'activationCurrency' in entity && typeof entity.activationCurrency === 'string'
    ? entity.activationCurrency
    : undefined
}

/**
 * Extract requirement from an entity
 * @param entity - The entity to extract from
 * @returns The requirement or undefined
 */
export function getRequirement(entity: SURefMetaEntity): string[] | undefined {
  return 'requirement' in entity && Array.isArray(entity.requirement)
    ? (entity.requirement as string[])
    : undefined
}

/**
 * Extract chassisAbilities from an entity
 * @param entity - The entity to extract from
 * @returns The chassisAbilities or undefined
 */
export function getChassisAbilities(entity: SURefMetaEntity): unknown | undefined {
  return 'chassisAbilities' in entity ? entity.chassisAbilities : undefined
}

/**
 * Extract patterns from an entity
 * @param entity - The entity to extract from
 * @returns The patterns or undefined
 */
export function getPatterns(entity: SURefMetaEntity): SURefObjectPattern[] | undefined {
  return 'patterns' in entity && Array.isArray(entity.patterns) ? entity.patterns : undefined
}

/**
 * Extract maxAbilities from an entity
 * @param entity - The entity to extract from
 * @returns The maxAbilities or undefined
 */
export function getMaxAbilities(entity: SURefMetaEntity): number | undefined {
  return 'maxAbilities' in entity && typeof entity.maxAbilities === 'number'
    ? entity.maxAbilities
    : undefined
}

/**
 * Extract advanceable from an entity
 * @param entity - The entity to extract from
 * @returns The advanceable or undefined
 */
export function getAdvanceable(entity: SURefMetaEntity): boolean | undefined {
  return 'advanceable' in entity && typeof entity.advanceable === 'boolean'
    ? entity.advanceable
    : undefined
}

/**
 * Extract coreTrees from an entity
 * @param entity - The entity to extract from
 * @returns The coreTrees or undefined
 */
export function getCoreTrees(entity: SURefMetaEntity): string[] | undefined {
  return 'coreTrees' in entity && Array.isArray(entity.coreTrees)
    ? (entity.coreTrees as string[])
    : undefined
}

/**
 * Extract damagedEffect from an entity
 * @param entity - The entity to extract from
 * @returns The damagedEffect or undefined
 */
export function getDamagedEffect(entity: SURefMetaEntity): string | undefined {
  return 'damagedEffect' in entity && typeof entity.damagedEffect === 'string'
    ? entity.damagedEffect
    : undefined
}

/**
 * Extract populationMin from an entity
 * @param entity - The entity to extract from
 * @returns The populationMin or undefined
 */
export function getPopulationMin(entity: SURefMetaEntity): number | undefined {
  return 'populationMin' in entity && typeof entity.populationMin === 'number'
    ? entity.populationMin
    : undefined
}

/**
 * Extract populationMax from an entity
 * @param entity - The entity to extract from
 * @returns The populationMax or undefined
 */
export function getPopulationMax(entity: SURefMetaEntity): number | undefined {
  return 'populationMax' in entity && typeof entity.populationMax === 'number'
    ? entity.populationMax
    : undefined
}

/**
 * Extract bonusPerTechLevel from an entity
 * @param entity - The entity to extract from
 * @returns The bonusPerTechLevel or undefined
 */
export function getBonusPerTechLevel(
  entity: SURefMetaEntity
): SURefObjectBonusPerTechLevel | undefined {
  return 'bonusPerTechLevel' in entity &&
    entity.bonusPerTechLevel !== null &&
    typeof entity.bonusPerTechLevel === 'object' &&
    !Array.isArray(entity.bonusPerTechLevel)
    ? entity.bonusPerTechLevel
    : undefined
}

/**
 * Extract section from an entity
 * @param entity - The entity to extract from
 * @returns The section or undefined
 */
export function getSection(entity: SURefMetaEntity): string | undefined {
  return 'section' in entity && typeof entity.section === 'string' ? entity.section : undefined
}

/**
 * Extract damageType from an entity
 * @param entity - The entity to extract from
 * @returns The damageType or undefined
 */
export function getDamageType(entity: SURefMetaEntity): unknown | undefined {
  return 'damageType' in entity ? entity.damageType : undefined
}

// Import object types used in property extractors
import type {
  SURefObjectBonusPerTechLevel,
  SURefObjectChoice,
  SURefObjectGrant,
  SURefObjectNpc,
  SURefObjectPattern,
  SURefObjectTable,
  SURefObjectTrait,
} from './types/objects.js'
