/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/generateUtilities.ts
 * 
 * Type guards and property extractors generated from JSON schemas
 */

import type { SURefMetaEntity } from './types/index.js'
// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard to check if an entity is a Ability
 * @param entity - The entity to check
 * @returns True if the entity is a Ability
 */
export function isAbility(entity: SURefMetaEntity): entity is SURefAbility {
  return (
    'tree' in entity &&
    'level' in entity
  )
}

/**
 * Type guard to check if an entity is a AbilityTreeRequirement
 * @param entity - The entity to check
 * @returns True if the entity is a AbilityTreeRequirement
 */
export function isAbilityTreeRequirement(entity: SURefMetaEntity): entity is SURefAbilityTreeRequirement {
  return (
    'requirement' in entity
  )
}

/**
 * Type guard to check if an entity is a BioTitan
 * @param entity - The entity to check
 * @returns True if the entity is a BioTitan
 */
export function isBioTitan(entity: SURefMetaEntity): entity is SURefBioTitan {
  return (
    'structurePoints' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Chassis
 * @param entity - The entity to check
 * @returns True if the entity is a Chassis
 */
export function isChassis(entity: SURefMetaEntity): entity is SURefChassis {
  return (
    'chassisAbilities' in entity &&
    'patterns' in entity
  )
}

/**
 * Type guard to check if an entity is a CoreClass
 * @param entity - The entity to check
 * @returns True if the entity is a CoreClass
 */
export function isCoreClass(entity: SURefMetaEntity): entity is SURefCoreClass {
  return (
    'maxAbilities' in entity &&
    'advanceable' in entity &&
    'coreTrees' in entity
  )
}

/**
 * Type guard to check if an entity is a CrawlerBay
 * @param entity - The entity to check
 * @returns True if the entity is a CrawlerBay
 */
export function isCrawlerBay(entity: SURefMetaEntity): entity is SURefCrawlerBay {
  return (
    'damagedEffect' in entity &&
    'npc' in entity
  )
}

/**
 * Type guard to check if an entity is a CrawlerTechLevel
 * @param entity - The entity to check
 * @returns True if the entity is a CrawlerTechLevel
 */
export function isCrawlerTechLevel(entity: SURefMetaEntity): entity is SURefCrawlerTechLevel {
  return (
    'techLevel' in entity &&
    'structurePoints' in entity &&
    'populationMin' in entity &&
    'populationMax' in entity
  )
}

/**
 * Type guard to check if an entity is a Crawler
 * @param entity - The entity to check
 * @returns True if the entity is a Crawler
 */
export function isCrawler(entity: SURefMetaEntity): entity is SURefCrawler {
  return (
    'npc' in entity &&
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Creature
 * @param entity - The entity to check
 * @returns True if the entity is a Creature
 */
export function isCreature(entity: SURefMetaEntity): entity is SURefCreature {
  return (
    'hitPoints' in entity
  )
}

/**
 * Type guard to check if an entity is a Equipment
 * @param entity - The entity to check
 * @returns True if the entity is a Equipment
 */
export function isEquipment(entity: SURefMetaEntity): entity is SURefEquipment {
  return (
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a Meld
 * @param entity - The entity to check
 * @returns True if the entity is a Meld
 */
export function isMeld(entity: SURefMetaEntity): entity is SURefMeld {
  return (
    'actions' in entity
  )
}

/**
 * Type guard to check if an entity is a NPC
 * @param entity - The entity to check
 * @returns True if the entity is a NPC
 */
export function isNPC(entity: SURefMetaEntity): entity is SURefNPC {
  return (
    'hitPoints' in entity
  )
}

/**
 * Type guard to check if an entity is a RollTable
 * @param entity - The entity to check
 * @returns True if the entity is a RollTable
 */
export function isRollTable(entity: SURefMetaEntity): entity is SURefRollTable {
  return (
    'section' in entity &&
    'table' in entity
  )
}

/**
 * Type guard to check if an entity is a Squad
 * @param entity - The entity to check
 * @returns True if the entity is a Squad
 */
export function isSquad(entity: SURefMetaEntity): entity is SURefSquad {
  return (
    'actions' in entity
  )
}


// Import types used in type guards
import type {
  SURefAbility,
  SURefAbilityTreeRequirement,
  SURefBioTitan,
  SURefChassis,
  SURefCoreClass,
  SURefCrawler,
  SURefCrawlerBay,
  SURefCrawlerTechLevel,
  SURefCreature,
  SURefEquipment,
  SURefMeld,
  SURefNPC,
  SURefRollTable,
  SURefSquad
} from './types/index.js'
// ============================================================================
// PROPERTY EXTRACTORS
// ============================================================================

/**
 * Extract techLevel from an entity
 * @param entity - The entity to extract from
 * @returns The techLevel or undefined
 */
export function getTechLevel(entity: SURefMetaEntity): number | undefined {
  return 'techLevel' in entity && typeof entity.techLevel === 'number'
    ? entity.techLevel
    : undefined
}

/**
 * Extract salvageValue from an entity
 * @param entity - The entity to extract from
 * @returns The salvageValue or undefined
 */
export function getSalvageValue(entity: SURefMetaEntity): number | undefined {
  return 'salvageValue' in entity && typeof entity.salvageValue === 'number'
    ? entity.salvageValue
    : undefined
}

/**
 * Extract structurePoints from an entity
 * @param entity - The entity to extract from
 * @returns The structurePoints or undefined
 */
export function getStructurePoints(entity: SURefMetaEntity): number | undefined {
  return 'structurePoints' in entity && typeof entity.structurePoints === 'number'
    ? entity.structurePoints
    : undefined
}

/**
 * Extract hitPoints from an entity
 * @param entity - The entity to extract from
 * @returns The hitPoints or undefined
 */
export function getHitPoints(entity: SURefMetaEntity): number | undefined {
  return 'hitPoints' in entity && typeof entity.hitPoints === 'number'
    ? entity.hitPoints
    : undefined
}

/**
 * Extract maxAbilities from an entity
 * @param entity - The entity to extract from
 * @returns The maxAbilities or undefined
 */
export function getMaxAbilities(entity: SURefMetaEntity): number | undefined {
  return 'maxAbilities' in entity && typeof entity.maxAbilities === 'number'
    ? entity.maxAbilities
    : undefined
}

/**
 * Extract level from an entity
 * @param entity - The entity to extract from
 * @returns The level or undefined
 */
export function getLevel(entity: SURefMetaEntity): string | number | undefined {
  return 'level' in entity &&
    (typeof entity.level === 'string' || typeof entity.level === 'number')
    ? entity.level
    : undefined
}

/**
 * Extract tree from an entity
 * @param entity - The entity to extract from
 * @returns The tree or undefined
 */
export function getTree(entity: SURefMetaEntity): string | undefined {
  return 'tree' in entity && typeof entity.tree === 'string'
    ? entity.tree
    : undefined
}

/**
 * Extract description from an entity
 * @param entity - The entity to extract from
 * @returns The description or undefined
 */
export function getDescription(entity: SURefMetaEntity): string | undefined {
  return 'description' in entity && typeof entity.description === 'string'
    ? entity.description
    : undefined
}

/**
 * Extract actions from an entity
 * @param entity - The entity to extract from
 * @returns The actions or undefined
 */
export function getActions(entity: SURefMetaEntity): SURefMetaAction[] | undefined {
  return 'actions' in entity && Array.isArray(entity.actions)
    ? entity.actions
    : undefined
}

/**
 * Extract grants from an entity
 * @param entity - The entity to extract from
 * @returns The grants or undefined
 */
export function getGrants(entity: SURefMetaEntity): SURefMetaGrant[] | undefined {
  return 'grants' in entity && Array.isArray(entity.grants)
    ? entity.grants
    : undefined
}

/**
 * Extract traits from an entity
 * @param entity - The entity to extract from
 * @returns The traits or undefined
 */
export function getTraits(entity: SURefMetaEntity): SURefMetaTraits | undefined {
  return 'traits' in entity && Array.isArray(entity.traits)
    ? entity.traits
    : undefined
}

/**
 * Extract mechActionType from an entity
 * @param entity - The entity to extract from
 * @returns The mechActionType or undefined
 */
export function getMechActionType(entity: SURefMetaEntity): string | undefined {
  return 'mechActionType' in entity && typeof entity.mechActionType === 'string'
    ? entity.mechActionType
    : undefined
}

/**
 * Extract activationCurrency from an entity
 * @param entity - The entity to extract from
 * @returns The activationCurrency or undefined
 */
export function getActivationCurrency(entity: SURefMetaEntity): string | undefined {
  return 'activationCurrency' in entity && typeof entity.activationCurrency === 'string'
    ? entity.activationCurrency
    : undefined
}

/**
 * Extract requirement from an entity
 * @param entity - The entity to extract from
 * @returns The requirement or undefined
 */
export function getRequirement(entity: SURefMetaEntity): string[] | undefined {
  return 'requirement' in entity && Array.isArray(entity.requirement)
    ? entity.requirement
    : undefined
}

/**
 * Extract chassisAbilities from an entity
 * @param entity - The entity to extract from
 * @returns The chassisAbilities or undefined
 */
export function getChassisAbilities(entity: SURefMetaEntity): SURefMetaAction[] | undefined {
  return 'chassisAbilities' in entity && Array.isArray(entity.chassisAbilities)
    ? entity.chassisAbilities
    : undefined
}

/**
 * Extract patterns from an entity
 * @param entity - The entity to extract from
 * @returns The patterns or undefined
 */
export function getPatterns(entity: SURefMetaEntity): SURefMetaPattern[] | undefined {
  return 'patterns' in entity && Array.isArray(entity.patterns)
    ? entity.patterns
    : undefined
}

/**
 * Extract npc from an entity
 * @param entity - The entity to extract from
 * @returns The npc or undefined
 */
export function getNpc(entity: SURefMetaEntity): SURefMetaNpc | undefined {
  return 'npc' in entity &&
    entity.npc !== null &&
    typeof entity.npc === 'object' &&
    !Array.isArray(entity.npc)
    ? entity.npc
    : undefined
}

/**
 * Extract advanceable from an entity
 * @param entity - The entity to extract from
 * @returns The advanceable or undefined
 */
export function getAdvanceable(entity: SURefMetaEntity): boolean | undefined {
  return 'advanceable' in entity && typeof entity.advanceable === 'boolean'
    ? entity.advanceable
    : undefined
}

/**
 * Extract coreTrees from an entity
 * @param entity - The entity to extract from
 * @returns The coreTrees or undefined
 */
export function getCoreTrees(entity: SURefMetaEntity): string[] | undefined {
  return 'coreTrees' in entity && Array.isArray(entity.coreTrees)
    ? entity.coreTrees
    : undefined
}

/**
 * Extract content from an entity
 * @param entity - The entity to extract from
 * @returns The content or undefined
 */
export function getContent(entity: SURefMetaEntity): SURefMetaContent | undefined {
  return 'content' in entity && Array.isArray(entity.content)
    ? entity.content
    : undefined
}

/**
 * Extract damagedEffect from an entity
 * @param entity - The entity to extract from
 * @returns The damagedEffect or undefined
 */
export function getDamagedEffect(entity: SURefMetaEntity): string | undefined {
  return 'damagedEffect' in entity && typeof entity.damagedEffect === 'string'
    ? entity.damagedEffect
    : undefined
}

/**
 * Extract choices from an entity
 * @param entity - The entity to extract from
 * @returns The choices or undefined
 */
export function getChoices(entity: SURefMetaEntity): SURefMetaChoices | undefined {
  return 'choices' in entity && Array.isArray(entity.choices)
    ? entity.choices
    : undefined
}

/**
 * Extract table from an entity
 * @param entity - The entity to extract from
 * @returns The table or undefined
 */
export function getTable(entity: SURefMetaEntity): SURefMetaTable | undefined {
  return 'table' in entity &&
    entity.table !== null &&
    typeof entity.table === 'object' &&
    !Array.isArray(entity.table)
    ? entity.table
    : undefined
}

/**
 * Extract populationMin from an entity
 * @param entity - The entity to extract from
 * @returns The populationMin or undefined
 */
export function getPopulationMin(entity: SURefMetaEntity): number | undefined {
  return 'populationMin' in entity && typeof entity.populationMin === 'number'
    ? entity.populationMin
    : undefined
}

/**
 * Extract populationMax from an entity
 * @param entity - The entity to extract from
 * @returns The populationMax or undefined
 */
export function getPopulationMax(entity: SURefMetaEntity): number | undefined {
  return 'populationMax' in entity && typeof entity.populationMax === 'number'
    ? entity.populationMax
    : undefined
}

/**
 * Extract bonusPerTechLevel from an entity
 * @param entity - The entity to extract from
 * @returns The bonusPerTechLevel or undefined
 */
export function getBonusPerTechLevel(entity: SURefMetaEntity): SURefMetaBonusPerTechLevel | undefined {
  return 'bonusPerTechLevel' in entity &&
    entity.bonusPerTechLevel !== null &&
    typeof entity.bonusPerTechLevel === 'object' &&
    !Array.isArray(entity.bonusPerTechLevel)
    ? entity.bonusPerTechLevel
    : undefined
}

/**
 * Extract section from an entity
 * @param entity - The entity to extract from
 * @returns The section or undefined
 */
export function getSection(entity: SURefMetaEntity): string | undefined {
  return 'section' in entity && typeof entity.section === 'string'
    ? entity.section
    : undefined
}

/**
 * Extract damageType from an entity
 * @param entity - The entity to extract from
 * @returns The damageType or undefined
 */
export function getDamageType(entity: SURefMetaEntity): string | undefined {
  return 'damageType' in entity && typeof entity.damageType === 'string'
    ? entity.damageType
    : undefined
}


// Import meta types used in property extractors
import type {
  SURefMetaAction,
  SURefMetaBonusPerTechLevel,
  SURefMetaChoices,
  SURefMetaContent,
  SURefMetaGrant,
  SURefMetaNpc,
  SURefMetaPattern,
  SURefMetaTable,
  SURefMetaTraits
} from './types/objects.js'
