/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod'
import { type Json } from './database-generated.types'

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable()
)

export const publicCargoRowSchema = z.object({
  amount: z.number().nullable(),
  crawler_id: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  mech_id: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  name: z.string(),
  schema_name: z.string().nullable(),
  schema_ref_id: z.string().nullable(),
  updated_at: z.string(),
})

export const publicCargoInsertSchema = z.object({
  amount: z.number().optional().nullable(),
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  mech_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  name: z.string(),
  schema_name: z.string().optional().nullable(),
  schema_ref_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
})

export const publicCargoUpdateSchema = z.object({
  amount: z.number().optional().nullable(),
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  mech_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  name: z.string().optional(),
  schema_name: z.string().optional().nullable(),
  schema_ref_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
})

export const publicCargoRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('cargo_crawler_id_fkey'),
    columns: z.tuple([z.literal('crawler_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('crawlers'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('cargo_mech_id_fkey'),
    columns: z.tuple([z.literal('mech_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('mechs'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicCrawlersRowSchema = z.object({
  active: z.boolean(),
  created_at: z.string().nullable(),
  current_damage: z.number().nullable(),
  description: z.string().nullable(),
  game_id: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  notes: z.string().nullable(),
  npc: jsonSchema.nullable(),
  scrap_tl_five: z.number().nullable(),
  scrap_tl_four: z.number().nullable(),
  scrap_tl_one: z.number().nullable(),
  scrap_tl_six: z.number().nullable(),
  scrap_tl_three: z.number().nullable(),
  scrap_tl_two: z.number().nullable(),
  tech_level: z.number().nullable(),
  updated_at: z.string().nullable(),
  upgrade: z.number().nullable(),
  user_id: z.string(),
})

export const publicCrawlersInsertSchema = z.object({
  active: z.boolean().optional(),
  created_at: z.string().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  game_id: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  notes: z.string().optional().nullable(),
  npc: jsonSchema.optional().nullable(),
  scrap_tl_five: z.number().optional().nullable(),
  scrap_tl_four: z.number().optional().nullable(),
  scrap_tl_one: z.number().optional().nullable(),
  scrap_tl_six: z.number().optional().nullable(),
  scrap_tl_three: z.number().optional().nullable(),
  scrap_tl_two: z.number().optional().nullable(),
  tech_level: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  upgrade: z.number().optional().nullable(),
  user_id: z.string(),
})

export const publicCrawlersUpdateSchema = z.object({
  active: z.boolean().optional(),
  created_at: z.string().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  game_id: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  notes: z.string().optional().nullable(),
  npc: jsonSchema.optional().nullable(),
  scrap_tl_five: z.number().optional().nullable(),
  scrap_tl_four: z.number().optional().nullable(),
  scrap_tl_one: z.number().optional().nullable(),
  scrap_tl_six: z.number().optional().nullable(),
  scrap_tl_three: z.number().optional().nullable(),
  scrap_tl_two: z.number().optional().nullable(),
  tech_level: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  upgrade: z.number().optional().nullable(),
  user_id: z.string().optional(),
})

export const publicExternalLinksRowSchema = z.object({
  created_at: z.string().nullable(),
  game_id: z.string(),
  id: z.string(),
  name: z.string(),
  updated_at: z.string().nullable(),
  url: z.string(),
})

export const publicExternalLinksInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  game_id: z.string(),
  id: z.string().optional(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
  url: z.string(),
})

export const publicExternalLinksUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  game_id: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  url: z.string().optional(),
})

export const publicGameInvitesRowSchema = z.object({
  code: z.string(),
  created_at: z.string().nullable(),
  created_by: z.string(),
  expires_at: z.string().nullable(),
  game_id: z.string(),
  id: z.string(),
  max_uses: z.number().nullable(),
  uses: z.number().nullable(),
})

export const publicGameInvitesInsertSchema = z.object({
  code: z.string(),
  created_at: z.string().optional().nullable(),
  created_by: z.string(),
  expires_at: z.string().optional().nullable(),
  game_id: z.string(),
  id: z.string().optional(),
  max_uses: z.number().optional().nullable(),
  uses: z.number().optional().nullable(),
})

export const publicGameInvitesUpdateSchema = z.object({
  code: z.string().optional(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  game_id: z.string().optional(),
  id: z.string().optional(),
  max_uses: z.number().optional().nullable(),
  uses: z.number().optional().nullable(),
})

export const publicGameInvitesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('game_invites_game_id_fkey'),
    columns: z.tuple([z.literal('game_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('games'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicGameMembersRowSchema = z.object({
  game_id: z.string(),
  id: z.string(),
  joined_at: z.string().nullable(),
  role: z.string(),
  user_id: z.string(),
})

export const publicGameMembersInsertSchema = z.object({
  game_id: z.string(),
  id: z.string().optional(),
  joined_at: z.string().optional().nullable(),
  role: z.string(),
  user_id: z.string(),
})

export const publicGameMembersUpdateSchema = z.object({
  game_id: z.string().optional(),
  id: z.string().optional(),
  joined_at: z.string().optional().nullable(),
  role: z.string().optional(),
  user_id: z.string().optional(),
})

export const publicGameMembersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('game_members_game_id_fkey'),
    columns: z.tuple([z.literal('game_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('games'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicGamesRowSchema = z.object({
  active: z.boolean(),
  created_at: z.string().nullable(),
  created_by: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  updated_at: z.string().nullable(),
})

export const publicGamesInsertSchema = z.object({
  active: z.boolean().optional(),
  created_at: z.string().optional().nullable(),
  created_by: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
})

export const publicGamesUpdateSchema = z.object({
  active: z.boolean().optional(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
})

export const publicMechsRowSchema = z.object({
  active: z.boolean(),
  appearance: z.string().nullable(),
  created_at: z.string().nullable(),
  current_damage: z.number().nullable(),
  current_ep: z.number().nullable(),
  current_heat: z.number().nullable(),
  id: z.string(),
  modules: z.array(z.string()).nullable(),
  notes: z.string().nullable(),
  pattern: z.string().nullable(),
  pilot_id: z.string().nullable(),
  quirk: z.string().nullable(),
  systems: z.array(z.string()).nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
})

export const publicMechsInsertSchema = z.object({
  active: z.boolean().optional(),
  appearance: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  current_ep: z.number().optional().nullable(),
  current_heat: z.number().optional().nullable(),
  id: z.string().optional(),
  modules: z.array(z.string()).optional().nullable(),
  notes: z.string().optional().nullable(),
  pattern: z.string().optional().nullable(),
  pilot_id: z.string().optional().nullable(),
  quirk: z.string().optional().nullable(),
  systems: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
})

export const publicMechsUpdateSchema = z.object({
  active: z.boolean().optional(),
  appearance: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  current_ep: z.number().optional().nullable(),
  current_heat: z.number().optional().nullable(),
  id: z.string().optional(),
  modules: z.array(z.string()).optional().nullable(),
  notes: z.string().optional().nullable(),
  pattern: z.string().optional().nullable(),
  pilot_id: z.string().optional().nullable(),
  quirk: z.string().optional().nullable(),
  systems: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
})

export const publicMechsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('mechs_pilot_id_fkey'),
    columns: z.tuple([z.literal('pilot_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('pilots'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicPilotsRowSchema = z.object({
  abilities: z.array(z.string()).nullable(),
  active: z.boolean(),
  appearance: z.string().nullable(),
  background: z.string().nullable(),
  background_used: z.boolean().nullable(),
  callsign: z.string(),
  crawler_id: z.string().nullable(),
  created_at: z.string().nullable(),
  current_ap: z.number().nullable(),
  current_damage: z.number().nullable(),
  current_tp: z.number().nullable(),
  equipment: z.array(z.string()).nullable(),
  id: z.string(),
  keepsake: z.string().nullable(),
  keepsake_used: z.boolean().nullable(),
  max_ap: z.number().nullable(),
  max_hp: z.number().nullable(),
  motto: z.string().nullable(),
  motto_used: z.boolean().nullable(),
  notes: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
})

export const publicPilotsInsertSchema = z.object({
  abilities: z.array(z.string()).optional().nullable(),
  active: z.boolean().optional(),
  appearance: z.string().optional().nullable(),
  background: z.string().optional().nullable(),
  background_used: z.boolean().optional().nullable(),
  callsign: z.string(),
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_ap: z.number().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  current_tp: z.number().optional().nullable(),
  equipment: z.array(z.string()).optional().nullable(),
  id: z.string().optional(),
  keepsake: z.string().optional().nullable(),
  keepsake_used: z.boolean().optional().nullable(),
  max_ap: z.number().optional().nullable(),
  max_hp: z.number().optional().nullable(),
  motto: z.string().optional().nullable(),
  motto_used: z.boolean().optional().nullable(),
  notes: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
})

export const publicPilotsUpdateSchema = z.object({
  abilities: z.array(z.string()).optional().nullable(),
  active: z.boolean().optional(),
  appearance: z.string().optional().nullable(),
  background: z.string().optional().nullable(),
  background_used: z.boolean().optional().nullable(),
  callsign: z.string().optional(),
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_ap: z.number().optional().nullable(),
  current_damage: z.number().optional().nullable(),
  current_tp: z.number().optional().nullable(),
  equipment: z.array(z.string()).optional().nullable(),
  id: z.string().optional(),
  keepsake: z.string().optional().nullable(),
  keepsake_used: z.boolean().optional().nullable(),
  max_ap: z.number().optional().nullable(),
  max_hp: z.number().optional().nullable(),
  motto: z.string().optional().nullable(),
  motto_used: z.boolean().optional().nullable(),
  notes: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
})

export const publicPilotsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('pilots_crawler_id_fkey'),
    columns: z.tuple([z.literal('crawler_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('crawlers'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicPlayerChoicesRowSchema = z.object({
  choice_ref_id: z.string(),
  created_at: z.string(),
  entity_id: z.string().nullable(),
  id: z.string(),
  player_choice_id: z.string().nullable(),
  updated_at: z.string(),
  value: z.string(),
})

export const publicPlayerChoicesInsertSchema = z.object({
  choice_ref_id: z.string(),
  created_at: z.string().optional(),
  entity_id: z.string().optional().nullable(),
  id: z.string().optional(),
  player_choice_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  value: z.string(),
})

export const publicPlayerChoicesUpdateSchema = z.object({
  choice_ref_id: z.string().optional(),
  created_at: z.string().optional(),
  entity_id: z.string().optional().nullable(),
  id: z.string().optional(),
  player_choice_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  value: z.string().optional(),
})

export const publicPlayerChoicesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('player_choices_entity_id_fkey'),
    columns: z.tuple([z.literal('entity_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('suentities'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('player_choices_player_choice_id_fkey'),
    columns: z.tuple([z.literal('player_choice_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('player_choices'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicSuentitiesRowSchema = z.object({
  crawler_id: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  mech_id: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  pilot_id: z.string().nullable(),
  schema_name: z.string(),
  schema_ref_id: z.string(),
  updated_at: z.string(),
})

export const publicSuentitiesInsertSchema = z.object({
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  mech_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  pilot_id: z.string().optional().nullable(),
  schema_name: z.string(),
  schema_ref_id: z.string(),
  updated_at: z.string().optional(),
})

export const publicSuentitiesUpdateSchema = z.object({
  crawler_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  mech_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  pilot_id: z.string().optional().nullable(),
  schema_name: z.string().optional(),
  schema_ref_id: z.string().optional(),
  updated_at: z.string().optional(),
})

export const publicSuentitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('entities_crawler_id_fkey'),
    columns: z.tuple([z.literal('crawler_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('crawlers'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('entities_mech_id_fkey'),
    columns: z.tuple([z.literal('mech_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('mechs'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('entities_pilot_id_fkey'),
    columns: z.tuple([z.literal('pilot_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('pilots'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const publicCreateGameInviteArgsSchema = z.object({
  p_expires_at: z.string().optional(),
  p_game_id: z.string(),
  p_max_uses: z.number().optional(),
})

export const publicCreateGameInviteReturnsSchema = z.object({
  code: z.string(),
  created_at: z.string().nullable(),
  created_by: z.string(),
  expires_at: z.string().nullable(),
  game_id: z.string(),
  id: z.string(),
  max_uses: z.number().nullable(),
  uses: z.number().nullable(),
})

export const publicExpireInviteArgsSchema = z.object({
  p_invite_id: z.string(),
})

export const publicExpireInviteReturnsSchema = z.undefined()

export const publicGenerateInviteCodeArgsSchema = z.never()

export const publicGenerateInviteCodeReturnsSchema = z.string()

export const publicGetGameMembersArgsSchema = z.object({
  p_game_id: z.string(),
})

export const publicGetGameMembersReturnsSchema = z.array(
  z.object({
    id: z.string(),
    role: z.string(),
    user_email: z.string(),
    user_id: z.string(),
    user_name: z.string(),
  })
)

export const publicIsGameMediatorArgsSchema = z.object({
  game_uuid: z.string(),
  user_uuid: z.string(),
})

export const publicIsGameMediatorReturnsSchema = z.boolean()

export const publicIsGameMemberArgsSchema = z.object({
  game_uuid: z.string(),
  user_uuid: z.string(),
})

export const publicIsGameMemberReturnsSchema = z.boolean()

export const publicRedeemInviteCodeArgsSchema = z.object({
  invite_code: z.string(),
})

export const publicRedeemInviteCodeReturnsSchema = z.string()

export const publicTestAuthUidArgsSchema = z.never()

export const publicTestAuthUidReturnsSchema = z.array(
  z.object({
    jwt_role: z.string(),
    jwt_sub: z.string(),
    uid: z.string(),
  })
)

export const publicUserOwnsChoiceArgsSchema = z.object({
  choice_id: z.string(),
  user_id: z.string(),
})

export const publicUserOwnsChoiceReturnsSchema = z.boolean()
