/**
 * Auto-generated TypeScript common types from common.schema.json
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateCommonTypes.ts
 */

/**
 * Non-negative integer (0 or greater)
 */
export type SURefNonNegativeInteger = number

/**
 * Positive integer (1 or greater)
 */
export type SURefPositiveInteger = number

/**
 * Unique identifier for the entry
 */
export type SURefId = string

/**
 * URL to an image asset for this entry
 */
export type SURefAssetUrl = string

/**
 * Name of the entry
 */
export type SURefName = string

/**
 * Cost in ability points to activate an ability
 */
export type SURefActivationCost = number | 'X'

/**
 * Technology level of the item or entity
 */
export type SURefTechLevel = SURefNonNegativeInteger

/**
 * Salvage value in credits
 */
export type SURefSalvageValue = SURefNonNegativeInteger

/**
 * Hit points for creatures and personnel
 */
export type SURefHitPoints = SURefNonNegativeInteger

/**
 * Structure points for mechs, vehicles, and titans
 */
export type SURefStructurePoints = SURefPositiveInteger
