/**
 * Auto-generated TypeScript common types from common.schema.json
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateCommonTypes.ts
 */

/**
 * Non-negative integer (0 or greater)
 */
export type SURefCommonNonNegativeInteger = number

/**
 * Positive integer (1 or greater)
 */
export type SURefCommonPositiveInteger = number

/**
 * Unique identifier for the entry
 */
export type SURefCommonId = string

/**
 * URL to an image asset for this entry
 */
export type SURefCommonAssetUrl = string

/**
 * Cost in ability points to activate an ability
 */
export type SURefCommonActivationCost = number | 'X'

/**
 * Name of the entry
 */
export type SURefCommonName = string

/**
 * Technology level of the item or entity
 */
export type SURefCommonTechLevel = SURefCommonNonNegativeInteger

/**
 * Salvage value in credits
 */
export type SURefCommonSalvageValue = SURefCommonNonNegativeInteger

/**
 * Hit points for creatures and personnel
 */
export type SURefCommonHitPoints = SURefCommonNonNegativeInteger

/**
 * Structure points for mechs, vehicles, and titans
 */
export type SURefCommonStructurePoints = SURefCommonPositiveInteger
