/**
 * Auto-generated TypeScript enum types from enums.schema.json
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateEnumTypes.ts
 */

/**
 * Type of action required to use an ability
 */
export type SURefEnumActionType =
  | 'Passive'
  | 'Free'
  | 'Reaction'
  | 'Turn'
  | 'Short'
  | 'Long'
  | 'DownTime'

/**
 * Type of advanced class
 */
export type SURefEnumClassType =
  | 'Advanced'
  | 'Hybrid'

/**
 * Type of content block for rendering structured text
 */
export type SURefEnumContentType =
  | 'paragraph'
  | 'heading'
  | 'list-item'
  | 'label'
  | 'datavalues'
  | 'hint'

/**
 * Type of damage
 */
export type SURefEnumDamageType =
  | 'HP'
  | 'SP'

/**
 * Individual range value
 */
export type SURefEnumRangeItem =
  | 'Close'
  | 'Medium'
  | 'Long'
  | 'Far'

/**
 * Range bands for abilities and weapons
 */
export type SURefEnumRange = SURefEnumRangeItem[]

/**
 * Name of the schema
 */
export type SURefEnumSchemaName =
  | 'abilities'
  | 'ability-tree-requirements'
  | 'bio-titans'
  | 'chassis'
  | 'classes.advanced'
  | 'classes.core'
  | 'crawler-bays'
  | 'crawler-tech-levels'
  | 'crawlers'
  | 'creatures'
  | 'distances'
  | 'drones'
  | 'equipment'
  | 'keywords'
  | 'meld'
  | 'modules'
  | 'npcs'
  | 'roll-tables'
  | 'squads'
  | 'systems'
  | 'traits'
  | 'vehicles'

/**
 * The source book or expansion for this content
 */
export type SURefEnumSource =
  | 'Salvage Union Workshop Manual'
  | 'Mech Monday'

/**
 * Ability tree name
 */
export type SURefEnumTree =
  | 'Advanced Engineer'
  | 'Advanced Hacking'
  | 'Advanced Hauler'
  | 'Advanced Scout'
  | 'Advanced Soldier'
  | 'Augmentation'
  | 'Cyborg'
  | 'Electronics'
  | 'Fabricator'
  | 'Forging'
  | 'Generic'
  | 'Gladitorial Combat'
  | 'Hacking'
  | 'Leadership'
  | 'Legendary Cyborg'
  | 'Legendary Engineer'
  | 'Legendary Fabricator'
  | 'Legendary Hacker'
  | 'Legendary Hauler'
  | 'Legendary Ranger'
  | 'Legendary Scout'
  | 'Legendary Smuggler'
  | 'Legendary Soldier'
  | 'Legendary Union Rep'
  | 'Mech-Tech'
  | 'Mechanical Knowledge'
  | 'Ranger'
  | 'Recon'
  | 'Salvaging'
  | 'Sleuth'
  | 'Smuggler'
  | 'Sniper'
  | 'Survivalist'
  | 'Tactical Warfare'
  | 'Trading'
  | 'Union Rep'
