/**
 * Auto-generated TypeScript type exports
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateTypeIndex.ts
 */

// Import types for use in union types
import type {
  SURefAbility,
  SURefBioTitan,
  SURefChassis,
  SURefClass,
  SURefCrawler,
  SURefCrawlerBay,
  SURefCreature,
  SURefDistance,
  SURefDrone,
  SURefEquipment,
  SURefKeyword,
  SURefMeld,
  SURefMetaAbilityTreeRequirement,
  SURefMetaAction,
  SURefMetaChassisAbility,
  SURefMetaCrawlerTechLevel,
  SURefModule,
  SURefNPC,
  SURefRollTable,
  SURefSquad,
  SURefSystem,
  SURefTrait,
  SURefVehicle,
} from './schemas.js'

// Export all enum types
export type * from './enums.js'

// Export all common types
export type * from './common.js'

// Export all object types
export type * from './objects.js'

// Export all schema types
export type * from './schemas.js'

// Re-export specific commonly used types for convenience
export type {
  SURefEnumSchemaName,
  SURefEnumTree,
  SURefEnumActionType,
  SURefEnumDamageType,
  SURefEnumRange,
  SURefEnumSource,
  SURefEnumClassType,
  SURefEnumContentType,
} from './enums.js'

export type {
  SURefCommonId,
  SURefCommonName,
  SURefCommonTechLevel,
  SURefCommonSalvageValue,
  SURefCommonHitPoints,
  SURefCommonStructurePoints,
  SURefCommonPositiveInteger,
  SURefCommonNonNegativeInteger,
  SURefCommonActivationCost,
  SURefCommonAssetUrl,
} from './common.js'

export type {
  SURefObjectTrait,
  SURefObjectStats,
  SURefObjectChassisStats,
  SURefObjectEquipmentStats,
  SURefObjectDataValue,
  SURefObjectChoice,
  SURefObjectNpc,
  SURefObjectSystemModule,
  SURefObjectTable,
  SURefObjectAdvancedClass,
  SURefObjectAction,
  SURefObjectGrant,
  SURefObjectChoices,
  SURefObjectContent,
  SURefObjectContentBlock,
  SURefObjectPattern,
  SURefObjectSystems,
  SURefObjectModules,
  SURefObjectTraits,
  SURefObjectBaseEntity,
  SURefObjectCombatEntity,
  SURefObjectMechanicalEntity,
  SURefObjectSchemaName,
} from './objects.js'

// Union type of all entity types (excludes meta schemas and non-entities)
export type SURefEntity =
  | SURefAbility
  | SURefBioTitan
  | SURefChassis
  | SURefClass
  | SURefCrawler
  | SURefCrawlerBay
  | SURefCreature
  | SURefDistance
  | SURefDrone
  | SURefEquipment
  | SURefKeyword
  | SURefMeld
  | SURefModule
  | SURefNPC
  | SURefRollTable
  | SURefSquad
  | SURefSystem
  | SURefTrait
  | SURefVehicle

// Union type of all meta entity types (includes all schemas except non-entities)
export type SURefMetaEntity =
  | SURefAbility
  | SURefBioTitan
  | SURefChassis
  | SURefClass
  | SURefCrawler
  | SURefCrawlerBay
  | SURefCreature
  | SURefDistance
  | SURefDrone
  | SURefEquipment
  | SURefKeyword
  | SURefMeld
  | SURefMetaAbilityTreeRequirement
  | SURefMetaAction
  | SURefMetaChassisAbility
  | SURefMetaCrawlerTechLevel
  | SURefModule
  | SURefNPC
  | SURefRollTable
  | SURefSquad
  | SURefSystem
  | SURefTrait
  | SURefVehicle
