/**
 * Auto-generated TypeScript object and array types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateObjectTypes.ts
 */

import type {
  SURefActionType,
  SURefClassType,
  SURefContentType,
  SURefDamageType,
  SURefRange,
  SURefSchemaName,
  SURefSource,
  SURefTree
} from './enums.js'

import type {
  SURefActivationCost,
  SURefAssetUrl,
  SURefHitPoints,
  SURefId,
  SURefName,
  SURefNonNegativeInteger,
  SURefPositiveInteger,
  SURefSalvageValue,
  SURefTechLevel
} from './common.js'

/**
 * Basic entity with name, content, source, and page reference
 */
export interface SURefMetaBaseEntity {
  asset_url?: SURefAssetUrl
  content?: SURefMetaContent
  id: SURefId
  indexable?: boolean
  name: SURefName
  source: SURefSource
  page: SURefPositiveInteger
}

/**
 * Special traits and properties of items, systems, or abilities
 */
export interface SURefMetaTrait {
  amount?: (SURefNonNegativeInteger | string)
  type: string
}

/**
 * Statistics for mechs, chassis, and vehicles
 */
export interface SURefMetaStats {
  structurePoints?: SURefNonNegativeInteger
  energyPoints?: SURefNonNegativeInteger
  heatCapacity?: SURefNonNegativeInteger
  systemSlots?: SURefNonNegativeInteger
  moduleSlots?: SURefNonNegativeInteger
  cargoCapacity?: SURefNonNegativeInteger
  techLevel?: SURefTechLevel
  salvageValue?: SURefSalvageValue
}

/**
 * Statistics specific to chassis
 */
export interface SURefMetaChassisStats {
  structurePoints?: SURefNonNegativeInteger
  energyPoints?: SURefNonNegativeInteger
  heatCapacity?: SURefNonNegativeInteger
  systemSlots?: SURefNonNegativeInteger
  moduleSlots?: SURefNonNegativeInteger
  cargoCapacity?: SURefNonNegativeInteger
  techLevel?: SURefTechLevel
  salvageValue?: SURefSalvageValue
}

/**
 * Statistics for equipment (systems and modules)
 */
export interface SURefMetaEquipmentStats {
  techLevel?: SURefTechLevel
  salvageValue?: SURefSalvageValue
}

/**
 * A data value with label, optional value, and optional type
 */
export interface SURefMetaDataValue {
  /**
   * The label for this data value
   */
  label: (string | number)
  /**
   * Optional value for this data value
   */
  value?: (string | number)
  /**
   * Optional type for this data value (e.g., 'cost', 'keyword', 'trait', 'meta')
   */
  type?: string
}

/**
 * Block of structured content for rendering (paragraph, heading, list item, etc.)
 */
export interface SURefMetaContentBlock {
  type?: SURefContentType
  value?: (string | SURefMetaDataValue[])
  /**
   * Optional label for this content block (e.g., for labeled sections)
   */
  label?: string
  /**
   * Heading level (1-6) when type is 'heading'
   */
  level?: number
  /**
   * Nested content blocks (e.g., list items within a list)
   */
  items?: SURefMetaContentBlock[]
}

/**
 * Entity that can perform actions and has traits
 */
export interface SURefMetaCombatEntity {
  actions?: SURefMetaAction[]
  traits?: SURefMetaTrait[]
}

/**
 * Mechanical entity with structure points and equipment stats
 */
export interface SURefMetaMechanicalEntity {
  structurePoints?: SURefPositiveInteger
  techLevel?: SURefTechLevel
  salvageValue?: SURefSalvageValue
  systems?: string[]
  traits?: SURefMetaTrait[]
}

export interface SURefMetaChoice {
  id: SURefId
  name: SURefName
  content?: SURefMetaContent
  rollTable?: string
  schemaEntities?: string[]
  schema?: SURefSchemaName[]
  customSystemOptions?: SURefMetaSystemModule[]
  constraints?: {
    field?: string
    min?: SURefNonNegativeInteger
    max?: SURefNonNegativeInteger
  }
}

/**
 * NPC associated with an entity
 */
export interface SURefMetaNpc {
  position: SURefName
  content?: SURefMetaContent
  hitPoints: SURefHitPoints
  choices?: SURefMetaChoices
}

export interface SURefMetaPatternSystemModule {
  name: SURefName
  count?: SURefNonNegativeInteger
  /**
   * Preselected choices for this system or module, keyed by choice ID
   */
  preselectedChoices?: Record<string, SURefName>
}

/**
 * Effect that scales with tech level
 */
export interface SURefMetaTechLevelEffect {
  techLevelMin: SURefPositiveInteger
  techLevelMax: SURefPositiveInteger
  effects: {
label?: string
value: string
}[]
}

/**
 * An action, ability, or attack that can be performed
 */
export interface SURefMetaAction {
  id: SURefId
  content?: SURefMetaContent
  structurePoints?: number
  energyPoints?: number
  heatCapacity?: number
  systemSlots?: number
  moduleSlots?: number
  cargoCapacity?: number
  techLevel?: SURefTechLevel
  salvageValue?: number
  name: SURefName
  activationCost?: SURefActivationCost
  range?: SURefRange
  actionType?: SURefActionType
  traits?: SURefMetaTrait[]
  /**
   * Damage dealt by an attack or ability
   */
  damage?: {
    damageType: SURefDamageType
    amount: (SURefNonNegativeInteger | string)
  }
  choices?: SURefMetaChoice[]
  table?: SURefMetaTable
}

/**
 * Grantable entity with a name and description
 */
export interface SURefMetaGrant {
  schema: (SURefSchemaName | 'choice')
  name: SURefName
}

/**
 * Mech chassis pattern configuration
 */
export interface SURefMetaPattern {
  name: SURefName
  content?: SURefMetaContent
  legalStarting?: boolean
  systems: SURefMetaPatternSystemModule[]
  modules: SURefMetaPatternSystemModule[]
  /**
   * Optional drone configuration
   */
  drone?: {
    systems: string[]
    modules: string[]
  }
}

/**
 * A system or module that can be installed on a mech
 */
export interface SURefMetaSystemModule extends SURefMetaStats {
  techLevel: SURefTechLevel
  slotsRequired: SURefNonNegativeInteger
  salvageValue: SURefSalvageValue
  recommended?: boolean
  count?: SURefNonNegativeInteger
  actions: SURefMetaAction[]
}

/**
 * Bonus values that increase with tech level
 */
export type SURefMetaBonusPerTechLevel = SURefMetaStats

/**
 * Advanced or hybrid character class
 */
export interface SURefMetaAdvancedClass extends SURefMetaBaseEntity {
  type: SURefClassType
  advancedTree: SURefTree
  legendaryTree: SURefTree
  content?: SURefMetaContent
}

export type SURefMetaSchemaName =
  SURefSchemaName
  | 'actions'

/**
 * Roll table for random outcomes based on d20 rolls
 */
export type SURefMetaTable =
  {
      /**
       * Critical failure outcome
       */
      '1': string
      /**
       * Critical success outcome
       */
      '20': string
      type: 'standard'
      /**
       * High success outcome
       */
      '11-19': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      type: 'alternate'
      /**
       * Critical success outcome
       */
      '19-20': string
      /**
       * High success outcome
       */
      '11-18': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      '6': string
      '7': string
      '8': string
      '9': string
      '10': string
      '11': string
      '12': string
      '13': string
      '14': string
      '15': string
      '16': string
      '17': string
      '18': string
      '19': string
      '20': string
      type: 'flat'
    }

export type SURefMetaActionOptions = {
  label: string
  value: string
}[]

export type SURefMetaChoices = SURefMetaChoice[]

export type SURefMetaContent = SURefMetaContentBlock[]

export type SURefMetaCustomSystemOptions = SURefMetaSystemModule[]

export type SURefMetaModules = string[]

export type SURefMetaSchemaEntities = string[]

export type SURefMetaSchemaNames = SURefSchemaName[]

export type SURefMetaSystems = string[]

export type SURefMetaTechLevelEffects = SURefMetaTechLevelEffect[]

export type SURefMetaTraits = SURefMetaTrait[]
