/**
 * Auto-generated TypeScript object and array types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateObjectTypes.ts
 */

import type {
  SURefEnumActionType,
  SURefEnumClassType,
  SURefEnumContentType,
  SURefEnumDamageType,
  SURefEnumRange,
  SURefEnumSchemaName,
  SURefEnumSource,
  SURefEnumTree
} from './enums.js'

import type {
  SURefCommonActivationCost,
  SURefCommonAssetUrl,
  SURefCommonHitPoints,
  SURefCommonId,
  SURefCommonName,
  SURefCommonNonNegativeInteger,
  SURefCommonPositiveInteger,
  SURefCommonSalvageValue,
  SURefCommonTechLevel
} from './common.js'

/**
 * Special traits and properties of items, systems, or abilities
 */
export interface SURefObjectTrait {
  amount?: (SURefCommonNonNegativeInteger | string)
  type: string
}

/**
 * Statistics for mechs, chassis, and vehicles
 */
export interface SURefObjectStats {
  structurePoints?: SURefCommonNonNegativeInteger
  energyPoints?: SURefCommonNonNegativeInteger
  heatCapacity?: SURefCommonNonNegativeInteger
  systemSlots?: SURefCommonNonNegativeInteger
  moduleSlots?: SURefCommonNonNegativeInteger
  cargoCapacity?: SURefCommonNonNegativeInteger
  techLevel?: SURefCommonTechLevel
  salvageValue?: SURefCommonSalvageValue
}

/**
 * Statistics specific to chassis
 */
export interface SURefObjectChassisStats {
  structurePoints?: SURefCommonNonNegativeInteger
  energyPoints?: SURefCommonNonNegativeInteger
  heatCapacity?: SURefCommonNonNegativeInteger
  systemSlots?: SURefCommonNonNegativeInteger
  moduleSlots?: SURefCommonNonNegativeInteger
  cargoCapacity?: SURefCommonNonNegativeInteger
  techLevel?: SURefCommonTechLevel
  salvageValue?: SURefCommonSalvageValue
}

/**
 * Statistics for equipment (systems and modules)
 */
export interface SURefObjectEquipmentStats {
  techLevel?: SURefCommonTechLevel
  salvageValue?: SURefCommonSalvageValue
}

/**
 * Entity that can perform actions and has traits
 */
export interface SURefObjectCombatEntity {
  actions?: string[]
  traits?: SURefObjectTrait[]
}

/**
 * Mechanical entity with structure points and equipment stats
 */
export interface SURefObjectMechanicalEntity {
  structurePoints?: SURefCommonPositiveInteger
  techLevel?: SURefCommonTechLevel
  salvageValue?: SURefCommonSalvageValue
  systems?: string[]
  traits?: SURefObjectTrait[]
}

/**
 * NPC associated with an entity
 */
export interface SURefObjectNpc {
  position: SURefCommonName
  content?: SURefObjectContent
  hitPoints: SURefCommonHitPoints
  choices?: SURefObjectChoices
}

export interface SURefObjectPatternSystemModule {
  name: SURefCommonName
  count?: SURefCommonNonNegativeInteger
  /**
   * Preselected choices for this system or module, keyed by choice ID
   */
  preselectedChoices?: Record<string, SURefCommonName>
}

/**
 * A system or module that can be installed on a mech
 */
export interface SURefObjectSystemModule extends SURefObjectStats {
  techLevel: SURefCommonTechLevel
  slotsRequired: SURefCommonNonNegativeInteger
  salvageValue: SURefCommonSalvageValue
  recommended?: boolean
  count?: SURefCommonNonNegativeInteger
  actions: string[]
}

export interface SURefObjectChoice {
  id: SURefCommonId
  name: SURefCommonName
  content?: SURefObjectContent
  rollTable?: string
  schemaEntities?: string[]
  schema?: SURefEnumSchemaName[]
  customSystemOptions?: SURefObjectSystemModule[]
  setIndexable?: boolean
  constraints?: {
    field?: string
    min?: SURefCommonNonNegativeInteger
    max?: SURefCommonNonNegativeInteger
  }
}

/**
 * Basic entity with name, content, source, and page reference
 */
export interface SURefObjectBaseEntity {
  asset_url?: SURefCommonAssetUrl
  content?: SURefObjectContent
  id: SURefCommonId
  indexable?: boolean
  blackMarket?: boolean
  name: SURefCommonName
  source: SURefEnumSource
  page: SURefCommonPositiveInteger
}

/**
 * Bonus values that increase with tech level
 */
export type SURefObjectBonusPerTechLevel = SURefObjectStats

/**
 * Advanced or hybrid character class
 */
export interface SURefObjectAdvancedClass extends SURefObjectBaseEntity {
  type: SURefEnumClassType
  advancedTree: SURefEnumTree
  legendaryTree: SURefEnumTree
  content?: SURefObjectContent
}

/**
 * A data value with label, optional value, and optional type
 */
export interface SURefObjectDataValue {
  /**
   * The label for this data value
   */
  label: (string | number)
  /**
   * Optional value for this data value
   */
  value?: (string | number)
  /**
   * Optional type for this data value (e.g., 'cost', 'keyword', 'trait', 'meta')
   */
  type?: string
}

/**
 * Block of structured content for rendering (paragraph, heading, list item, etc.)
 */
export interface SURefObjectContentBlock {
  type?: SURefEnumContentType
  value?: (string | SURefObjectDataValue[])
  /**
   * Optional label for this content block (e.g., for labeled sections)
   */
  label?: string
  /**
   * Heading level (1-6) when type is 'heading'
   */
  level?: number
  /**
   * Nested content blocks (e.g., list items within a list)
   */
  items?: SURefObjectContentBlock[]
}

/**
 * Grantable entity with a name and description
 */
export interface SURefObjectGrant {
  schema: (SURefEnumSchemaName | 'choice')
  name: SURefCommonName
}

/**
 * An action, ability, or attack that can be performed
 */
export interface SURefObjectAction {
  id: SURefCommonId
  content?: SURefObjectContent
  structurePoints?: number
  energyPoints?: number
  heatCapacity?: number
  systemSlots?: number
  moduleSlots?: number
  cargoCapacity?: number
  techLevel?: SURefCommonTechLevel
  salvageValue?: number
  name: SURefCommonName
  activationCost?: SURefCommonActivationCost
  range?: SURefEnumRange
  actionType?: SURefEnumActionType
  traits?: SURefObjectTrait[]
  /**
   * Damage dealt by an attack or ability
   */
  damage?: {
    damageType: SURefEnumDamageType
    amount: (SURefCommonNonNegativeInteger | string)
  }
  choices?: SURefObjectChoice[]
  table?: SURefObjectTable
  /**
   * If true, this action will not affect the rendering of the entity display
   */
  hidden?: boolean
}

/**
 * Mech chassis pattern configuration
 */
export interface SURefObjectPattern {
  name: SURefCommonName
  content?: SURefObjectContent
  legalStarting?: boolean
  systems: SURefObjectPatternSystemModule[]
  modules: SURefObjectPatternSystemModule[]
  /**
   * Optional drone configuration
   */
  drone?: {
    systems: string[]
    modules: string[]
  }
}

export type SURefObjectSchemaName =
  SURefEnumSchemaName
  | 'actions'

/**
 * Roll table for random outcomes based on d20 rolls
 */
export type SURefObjectTable =
  {
      /**
       * Critical failure outcome
       */
      '1': string
      /**
       * Critical success outcome
       */
      '20': string
      type: 'standard'
      /**
       * High success outcome
       */
      '11-19': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      type: 'alternate'
      /**
       * Critical success outcome
       */
      '19-20': string
      /**
       * High success outcome
       */
      '11-18': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      '6': string
      '7': string
      '8': string
      '9': string
      '10': string
      '11': string
      '12': string
      '13': string
      '14': string
      '15': string
      '16': string
      '17': string
      '18': string
      '19': string
      '20': string
      type: 'flat'
    }
  | {
      '20': string
      type: 'dramatic'
    }

export type SURefObjectActionOptions = {
  label: string
  value: string
}[]

export type SURefObjectChoices = SURefObjectChoice[]

export type SURefObjectContent = SURefObjectContentBlock[]

export type SURefObjectCustomSystemOptions = SURefObjectSystemModule[]

export type SURefObjectModules = string[]

export type SURefObjectSchemaEntities = string[]

export type SURefObjectSchemaNames = SURefEnumSchemaName[]

export type SURefObjectSystems = string[]

export type SURefObjectTraits = SURefObjectTrait[]
