/**
 * Auto-generated TypeScript schema types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateSchemaTypes.ts
 */

import type { SURefActionType, SURefDamageType, SURefTree } from './enums.js'

import type { SURefHitPoints, SURefPositiveInteger } from './common.js'

import type {
  SURefMetaAction,
  SURefMetaAdvancedClass,
  SURefMetaBaseEntity,
  SURefMetaBonusPerTechLevel,
  SURefMetaChassisStats,
  SURefMetaChoice,
  SURefMetaChoices,
  SURefMetaCombatEntity,
  SURefMetaContent,
  SURefMetaGrant,
  SURefMetaMechanicalEntity,
  SURefMetaNpc,
  SURefMetaPattern,
  SURefMetaStats,
  SURefMetaSystemModule,
  SURefMetaTable,
  SURefMetaTechLevelEffects,
  SURefMetaTrait,
} from './objects.js'

/**
 * Pilot abilities and skills in Salvage Union
 */
export interface SURefAbility extends SURefMetaBaseEntity {
  description?: string
  tree: SURefTree
  level: number | 'L' | 'G'
  mechActionType?: SURefActionType
  grants?: SURefMetaGrant[]
  activationCurrency?: 'Variable'
  actions?: SURefMetaAction[]
}

/**
 * Requirements for ability trees in Salvage Union
 */
export interface SURefAbilityTreeRequirement extends SURefMetaBaseEntity {
  /**
   * List of ability tree names required to access this tree
   */
  requirement: SURefTree[]
}

/**
 * Massive bio-engineered titan creatures in Salvage Union
 */
export interface SURefBioTitan extends SURefMetaBaseEntity {
  structurePoints: SURefPositiveInteger
  actions: SURefMetaAction[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
}

/**
 * Mech chassis definitions in Salvage Union
 */
export interface SURefChassis
  extends SURefMetaBaseEntity,
    SURefMetaChassisStats {
  chassisAbilities: SURefMetaAction[]
  patterns: SURefMetaPattern[]
  npc?: SURefMetaNpc
}

/**
 * Advanced and Hybrid character classes in Salvage Union
 */
export type SURefAdvancedClass = SURefMetaAdvancedClass

/**
 * Core character classes in Salvage Union
 */
export interface SURefCoreClass extends SURefMetaBaseEntity {
  /**
   * Maximum number of abilities this class can have
   */
  maxAbilities: number
  /**
   * Whether this class can advance to hybrid classes
   */
  advanceable: boolean
  /**
   * Core ability trees available to this class
   */
  coreTrees: SURefTree[]
  content?: SURefMetaContent
}

/**
 * Bays and facilities on Union Crawlers in Salvage Union
 */
export interface SURefCrawlerBay extends SURefMetaBaseEntity {
  /**
   * Effect when this bay is damaged
   */
  damagedEffect: string
  npc: SURefMetaNpc
  /**
   * Choices available to the player when interacting with the NPC
   */
  choices?: SURefMetaChoice[]
  actions: SURefMetaAction[]
  techLevelEffects: SURefMetaTechLevelEffects
  table?: SURefMetaTable
}

/**
 * Tech levels for Union Crawlers in Salvage Union
 */
export interface SURefCrawlerTechLevel extends SURefMetaBaseEntity {
  /**
   * Tech level (1-6)
   */
  techLevel: number
  /**
   * Structure points for this tech level
   */
  structurePoints: number
  /**
   * Minimum approximate population
   */
  populationMin: number
  /**
   * Maximum approximate population (0 means unlimited/25,000+)
   */
  populationMax: number
}

/**
 * Crawler vehicles in Salvage Union
 */
export interface SURefCrawler extends SURefMetaBaseEntity {
  npc: SURefMetaNpc
  actions: SURefMetaAction[]
}

/**
 * Creatures and wildlife in Salvage Union
 */
export interface SURefCreature
  extends SURefMetaBaseEntity,
    SURefMetaCombatEntity {
  hitPoints: SURefHitPoints
}

/**
 * Distances in Salvage Union are abstracted into the following Range categories. Both Pilots and Mechs use these Range categories for their movement as well as the effective distances for their weapons and other Abilities. The Mediator can factor in any other difference between the speed and distance of Pilots and Mechs based on the narrative and the situation.
 */
export interface SURefDistance extends SURefMetaBaseEntity {
  content?: SURefMetaContent
}

/**
 * Autonomous drones in Salvage Union
 */
export type SURefDrone = SURefMetaBaseEntity & SURefMetaMechanicalEntity

/**
 * Pilot equipment and gear in Salvage Union
 */
export interface SURefEquipment extends SURefMetaBaseEntity, SURefMetaStats {
  bonusPerTechLevel?: SURefMetaBonusPerTechLevel
  choices?: SURefMetaChoices
  actions: SURefMetaAction[]
}

/**
 * Game keywords and terminology in Salvage Union
 */
export interface SURefKeyword extends SURefMetaBaseEntity {
  content?: SURefMetaContent
}

/**
 * Meld-infected creatures in Salvage Union
 */
export interface SURefMeld extends SURefMetaBaseEntity {
  actions: SURefMetaAction[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
  /**
   * Salvage value of the meld creature
   */
  salvageValue?: number
  /**
   * Hit points of the meld creature
   */
  hitPoints?: number
  /**
   * Structure points of the meld creature
   */
  structurePoints?: number
}

/**
 * Mech modules in Salvage Union
 */
export type SURefModule = SURefMetaSystemModule & SURefMetaBaseEntity

/**
 * Non-player characters and people in Salvage Union
 */
export interface SURefNPC extends SURefMetaBaseEntity, SURefMetaCombatEntity {
  hitPoints: SURefHitPoints
}

/**
 * Random tables and roll tables in Salvage Union
 */
export interface SURefRollTable extends SURefMetaBaseEntity {
  /**
   * Section or category of the roll table
   */
  section: string
  table: SURefMetaTable
  content?: SURefMetaContent
}

/**
 * NPC squads and groups in Salvage Union
 */
export interface SURefSquad extends SURefMetaBaseEntity {
  hitPoints?: SURefHitPoints
  actions: SURefMetaAction[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
  damageType?: SURefDamageType
}

/**
 * Mech systems in Salvage Union
 */
export type SURefSystem = SURefMetaSystemModule & SURefMetaBaseEntity

/**
 * Traits and special properties in Salvage Union
 */
export interface SURefTrait extends SURefMetaBaseEntity {
  content?: SURefMetaContent
}

/**
 * Conventional vehicles in Salvage Union
 */
export type SURefVehicle = SURefMetaBaseEntity & SURefMetaMechanicalEntity
