/**
 * Auto-generated TypeScript schema types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateSchemaTypes.ts
 */

import type {
  SURefEnumActionType,
  SURefEnumDamageType,
  SURefEnumTree
} from './enums.js'

import type {
  SURefCommonHitPoints,
  SURefCommonPositiveInteger
} from './common.js'

import type {
  SURefObjectAction,
  SURefObjectAdvancedClass,
  SURefObjectBaseEntity,
  SURefObjectBonusPerTechLevel,
  SURefObjectChassisStats,
  SURefObjectChoice,
  SURefObjectChoices,
  SURefObjectCombatEntity,
  SURefObjectContent,
  SURefObjectGrant,
  SURefObjectMechanicalEntity,
  SURefObjectNpc,
  SURefObjectPattern,
  SURefObjectStats,
  SURefObjectSystemModule,
  SURefObjectTable,
  SURefObjectTrait
} from './objects.js'

/**
 * Pilot abilities and skills in Salvage Union
 */
export interface SURefAbility extends SURefObjectBaseEntity {
  description?: string
  tree: SURefEnumTree
  level: (number | 'L' | 'G')
  mechActionType?: SURefEnumActionType
  grants?: SURefObjectGrant[]
  activationCurrency?: 'Variable'
  actions?: string[]
}

/**
 * Requirements for ability trees in Salvage Union
 */
export interface SURefMetaAbilityTreeRequirement extends SURefObjectBaseEntity {
  /**
   * List of ability tree names required to access this tree
   */
  requirement: SURefEnumTree[]
}

/**
 * Actions, abilities, and attacks that can be performed in Salvage Union
 */
export type SURefMetaAction = SURefObjectAction

/**
 * Massive bio-engineered titan creatures in Salvage Union
 */
export interface SURefBioTitan extends SURefObjectBaseEntity {
  structurePoints: SURefCommonPositiveInteger
  actions: string[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefObjectTrait[]
}

/**
 * Chassis abilities for mech chassis in Salvage Union
 */
export type SURefMetaChassisAbility = SURefObjectAction

/**
 * Mech chassis definitions in Salvage Union
 */
export interface SURefChassis extends SURefObjectBaseEntity, SURefObjectChassisStats {
  /**
   * Array of chassis ability names that reference chassis-abilities.json
   */
  chassisAbilities: string[]
  patterns: SURefObjectPattern[]
  npc?: SURefObjectNpc
}

/**
 * Advanced and Hybrid character classes in Salvage Union
 */
export type SURefAdvancedClass = SURefObjectAdvancedClass

/**
 * Core character classes in Salvage Union
 */
export interface SURefCoreClass extends SURefObjectBaseEntity {
  /**
   * Maximum number of abilities this class can have
   */
  maxAbilities: number
  /**
   * Whether this class can advance to hybrid classes
   */
  advanceable: boolean
  /**
   * Core ability trees available to this class
   */
  coreTrees: SURefEnumTree[]
  content?: SURefObjectContent
}

/**
 * Bays and facilities on Union Crawlers in Salvage Union
 */
export interface SURefCrawlerBay extends SURefObjectBaseEntity {
  /**
   * Effect when this bay is damaged
   */
  damagedEffect: string
  npc: SURefObjectNpc
  /**
   * Choices available to the player when interacting with the NPC
   */
  choices?: SURefObjectChoice[]
  table?: SURefObjectTable
}

/**
 * Tech levels for Union Crawlers in Salvage Union
 */
export interface SURefMetaCrawlerTechLevel extends SURefObjectBaseEntity {
  /**
   * Tech level (1-6)
   */
  techLevel: number
  /**
   * Structure points for this tech level
   */
  structurePoints: number
  /**
   * Minimum approximate population
   */
  populationMin: number
  /**
   * Maximum approximate population (0 means unlimited/25,000+)
   */
  populationMax: number
}

/**
 * Crawler vehicles in Salvage Union
 */
export interface SURefCrawler extends SURefObjectBaseEntity {
  npc: SURefObjectNpc
  actions: string[]
}

/**
 * Creatures and wildlife in Salvage Union
 */
export interface SURefCreature extends SURefObjectBaseEntity, SURefObjectCombatEntity {
  hitPoints: SURefCommonHitPoints
}

/**
 * Distances in Salvage Union are abstracted into the following Range categories. Both Pilots and Mechs use these Range categories for their movement as well as the effective distances for their weapons and other Abilities. The Mediator can factor in any other difference between the speed and distance of Pilots and Mechs based on the narrative and the situation.
 */
export interface SURefDistance extends SURefObjectBaseEntity {
  content?: SURefObjectContent
}

/**
 * Autonomous drones in Salvage Union
 */
export type SURefDrone = SURefObjectBaseEntity & SURefObjectMechanicalEntity

/**
 * Pilot equipment and gear in Salvage Union
 */
export interface SURefEquipment extends SURefObjectBaseEntity, SURefObjectStats {
  bonusPerTechLevel?: SURefObjectBonusPerTechLevel
  choices?: SURefObjectChoices
  actions: string[]
}

/**
 * Game keywords and terminology in Salvage Union
 */
export interface SURefKeyword extends SURefObjectBaseEntity {
  content?: SURefObjectContent
}

/**
 * Meld-infected creatures in Salvage Union
 */
export interface SURefMeld extends SURefObjectBaseEntity {
  actions: string[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefObjectTrait[]
  /**
   * Salvage value of the meld creature
   */
  salvageValue?: number
  /**
   * Hit points of the meld creature
   */
  hitPoints?: number
  /**
   * Structure points of the meld creature
   */
  structurePoints?: number
}

/**
 * Mech modules in Salvage Union
 */
export type SURefModule = SURefObjectSystemModule & SURefObjectBaseEntity

/**
 * Non-player characters and people in Salvage Union
 */
export interface SURefNPC extends SURefObjectBaseEntity, SURefObjectCombatEntity {
  hitPoints: SURefCommonHitPoints
}

/**
 * Random tables and roll tables in Salvage Union
 */
export interface SURefRollTable extends SURefObjectBaseEntity {
  /**
   * Section or category of the roll table
   */
  section: string
  table: SURefObjectTable
  content?: SURefObjectContent
}

/**
 * NPC squads and groups in Salvage Union
 */
export interface SURefSquad extends SURefObjectBaseEntity {
  hitPoints?: SURefCommonHitPoints
  actions: string[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefObjectTrait[]
  damageType?: SURefEnumDamageType
}

/**
 * Mech systems in Salvage Union
 */
export type SURefSystem = SURefObjectSystemModule & SURefObjectBaseEntity

/**
 * Traits and special properties in Salvage Union
 */
export interface SURefTrait extends SURefObjectBaseEntity {
  content?: SURefObjectContent
}

/**
 * Conventional vehicles in Salvage Union
 */
export type SURefVehicle = SURefObjectBaseEntity & SURefObjectMechanicalEntity
